### ISSUE TITLE
getting hit with lots of npm ERR! codes and npm ERR! gyp

### ISSUE THREAD

**Issue by quakeob** [bottega-code-school/js-builder#11]
these are all my errors. I have tried to downgrade python and it still isn't working my guess is because the tutorial was made 4 years ago but im not 100% sure. 

6079 error code 1
6080 error path C:\Users\jakep\code\portfolio\node_modules\node-sass
6081 error command failed
6082 error command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
6083 error Building: C:\Program Files\nodejs\node.exe C:\Users\jakep\code\portfolio\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
6084 error gyp info it worked if it ends with ok
6084 error gyp verb cli [
6084 error gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
6084 error gyp verb cli   'C:\\Users\\jakep\\code\\portfolio\\node_modules\\node-gyp\\bin\\node-gyp.js',
6084 error gyp verb cli   'rebuild',
6084 error gyp verb cli   '--verbose',
6084 error gyp verb cli   '--libsass_ext=',
6084 error gyp verb cli   '--libsass_cflags=',
6084 error gyp verb cli   '--libsass_ldflags=',
6084 error gyp verb cli   '--libsass_library='
6084 error gyp verb cli ]
6084 error gyp info using node-gyp@3.8.0
6084 error gyp info using node@16.13.1 | win32 | x64
6084 error gyp verb command rebuild []
6084 error gyp verb command clean []
6084 error gyp verb clean removing "build" directory
6084 error gyp verb command configure []
6084 error gyp verb check python checking for Python executable "python2" in the PATH
6084 error gyp verb `which` failed Error: not found: python2
6084 error gyp verb `which` failed     at getNotFoundError (C:\Users\jakep\code\portfolio\node_modules\which\which.js:13:12)
6084 error gyp verb `which` failed     at F (C:\Users\jakep\code\portfolio\node_modules\which\which.js:68:19)
6084 error gyp verb `which` failed     at E (C:\Users\jakep\code\portfolio\node_modules\which\which.js:80:29)
6084 error gyp verb `which` failed     at C:\Users\jakep\code\portfolio\node_modules\which\which.js:89:16
6084 error gyp verb `which` failed     at C:\Users\jakep\code\portfolio\node_modules\isexe\index.js:42:5
6084 error gyp verb `which` failed     at C:\Users\jakep\code\portfolio\node_modules\isexe\windows.js:36:5
6084 error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
6084 error gyp verb `which` failed  python2 Error: not found: python2
6084 error gyp verb `which` failed     at getNotFoundError (C:\Users\jakep\code\portfolio\node_modules\which\which.js:13:12)
6084 error gyp verb `which` failed     at F (C:\Users\jakep\code\portfolio\node_modules\which\which.js:68:19)
6084 error gyp verb `which` failed     at E (C:\Users\jakep\code\portfolio\node_modules\which\which.js:80:29)
6084 error gyp verb `which` failed     at C:\Users\jakep\code\portfolio\node_modules\which\which.js:89:16
6084 error gyp verb `which` failed     at C:\Users\jakep\code\portfolio\node_modules\isexe\index.js:42:5
6084 error gyp verb `which` failed     at C:\Users\jakep\code\portfolio\node_modules\isexe\windows.js:36:5
6084 error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
6084 error gyp verb `which` failed   code: 'ENOENT'
6084 error gyp verb `which` failed }
6084 error gyp verb check python checking for Python executable "python" in the PATH
6084 error gyp verb `which` succeeded python C:\Python310\python.EXE
6084 error gyp ERR! configure error
6084 error gyp ERR! stack Error: Command failed: C:\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
6084 error gyp ERR! stack   File "<string>", line 1
6084 error gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
6084 error gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6084 error gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
6084 error gyp ERR! stack
6084 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
6084 error gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
6084 error gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
6084 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
6084 error gyp ERR! System Windows_NT 10.0.19042
6084 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jakep\\code\\portfolio\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
6084 error gyp ERR! cwd C:\Users\jakep\code\portfolio\node_modules\node-sass
6084 error gyp ERR! node -v v16.13.1
6084 error gyp ERR! node-gyp -v v3.8.0
6084 error gyp ERR! not ok
6084 error Build failed with error code: 1
6085 verbose exit 1

**Comment by bughazard** [comment]
Getting the same issues. Removing node-sass from the package.json file fixes it, but of course you then run into other problems while trying to compile because it's a dependency. Node-sass only installs if you get install of the most recent versions, which--again--breaks other parts of the program because the jump from version 4 to version 6 introduces a lot of changes.

**Comment by DANKOS-the-FIRST** [comment]
> Getting the same issues. Removing node-sass from the package.json file fixes it, but of course you then run into other problems while trying to compile because it's a dependency. Node-sass only installs if you get install of the most recent versions, which--again--breaks other parts of the program because the jump from version 4 to version 6 introduces a lot of changes.

So, can we use somehow this lib?

**Comment by bughazard** [comment]
> So, can we use somehow this lib?

I've figured out how to make it work, if you're still having troubles--remove node-sass from your package.json file. `npm install` should work at this point, so run it. Then, run `npm install sass`.
